# Exported from Render on 2026-04-28T00:28:05Z
version: "1"

services:
  - type: web
    name: vanguard-api-v3
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r api/requirements.txt
    startCommand: cd api && python run.py --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: vanguard dj
          property: connectionString

databases:
  - name: vanguard dj
    databaseName: vanguard_dj
    user: vanguard_dj_user
    plan: free
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: "18"

